### ISSUE TITLE
Does not work with Moodle 3.9.2+ (Build: 20200918)

### ISSUE THREAD

**Issue by aalexandrescu** [IITBombayWeb/moodle-quiz_downloadsubmissions#14]
I have downloaded version: quiz_downloadsubmissions_moodle39_2020100700 and copied the downloadsubmissions directory and all its contents to the .../mod/quiz/report directory in our Moodle installation.
After installation it looks like in the image:
![image](https://user-images.githubusercontent.com/12772281/102198088-a35c8e80-3eca-11eb-83b1-b5bdb56ca41d.png)
And in the results section of the Quiz menu it looks like this:
![image](https://user-images.githubusercontent.com/12772281/102198203-c8510180-3eca-11eb-9336-9fb3b34372d9.png)

**Comment by lucaboesch** [comment]
That's just a caching issue.
Please do purge the caches. Then that language string will be there.
This issue can be closed.

Best,
Luca

**Comment by aalexandrescu** [comment]
It was a problem with the group permissions on the directory.
Thank you.
